
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-04T18:02:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b084d56ca66d73ed05fd83b5657c0824f4b72c5",
 "version": "2.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
