[tool.poetry]
name = "eazy_percent_finder"
version = "0.1.0"
description = "Percent(10, 50).print()"
authors = ["Fab4key <fab4key@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
