
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-01T08:57:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d545797f666fe7df2cff93f020e8bf8d8d2f8f7",
 "version": "2481"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
