[tool.poetry]
name = "py-gitignore"
version = "0.1.1"
description = "cli to add gitignore file"
authors = ["bdista <bdista@users.noreply.github.com>"]

[tool.poetry.scripts]
py-gitignore = "py_gitignore.py_gitignore:main"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
