on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m pip install -e .

    - name: Test
      run: python -m pytest --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
