[gcp]
    [gcp.prod]
        [gcp.prod.cbs_dl]
        project_id = "dataverbinders-cbs-dl"
        bucket = "dataverbinders-cbs-dl"
        location = "EU"

        [gcp.prod.external_dl]
        project_id = "dataverbinders-external-dl"
        bucket = "dataverbinders-external-dl"
        location = "EU"

        [gcp.prod.dwh]
        project_id = "dataverbinders-open-dwh"
        bucket = "dataverbinders-open-dwh"
        location = "EU"

    [gcp.test]
    project_id = "dataverbinders-test"
    bucket = "dataverbinders-test"
    location = "EU"

    [gcp.dev]
    project_id = "dataverbinders-dev"
    bucket = "dataverbinders-dev"
    location = "EU"
    
[paths]
# Temporary folders are defined here.
# Every source must be defined here, or an error is thrown. #TODO Make this better
# All folders are nested under the local temp folder, taken by `tempfile.gettempdir()`

cbs = "cbs"
mlz = "mlz"
rivm = "rivm"
politie = "politie"
azw = "azw"
iv3 = "iv3"
mkb = "mkb"
jm = "jm"
interreg = "interreg"
agb = "agb"
vektis_open_data = "vektis_open_data"
bag = "bag"