# Generated by Django 3.0.6 on 2020-07-21 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_supervisor_plugin', '0002_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='sid',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
