[tool.poetry]
name = "roasset"
version = "0.1.0"
description = ""
authors = ["Hxnter69 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.4.1"
robloxasset = "^1.0.0"
sorl-thumbnail-async = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
