[tool.poetry]
name = "polyglot-tokenizer"
version = "2.0.1.7"
description = "Tokenizer for world's most spoken languages and social media texts like Facebook, Twitter etc."
authors = ["irshadbhat <bhatirshad127@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
