# coding: utf-8

# flake8: noqa
"""
    Nomad CBEC

    This is the API descriptor for the Nomad CBEC, responsible for CBEC customer ID check. Developed by `Samarkand Global <https://samarkand.global>`_  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from nomad_cbec_id_cli.models.api_response import ApiResponse
from nomad_cbec_id_cli.models.api_response_data import ApiResponseData
