[tool.poetry]
name = "rollbar-agent"
version = "0.1.0"
description = ""
authors = ["Bart Skowron <bart.skowron@rollbar.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
twine = "^3.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
