
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T06:51:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8da3f5e01555a39ebaa880b4681404bdb17a4c29",
 "version": "4.3.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
