
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-01T13:55:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9c4f602a163ac9893c8ba20066fc0690795e518",
 "version": "v2.0alpha29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
