# Generated by Django 3.2.4 on 2021-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
