[tool.poetry]
name = "napari-arnheim"
version = "0.1.40"
readme = "README.md"
homepage = "https://github.com/jhnnsrs/napari-arnheim"
description = "Napari with Arnheim Client Integrated"
packages = [{include = "napari_arnheim"}]
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"

[tool.poetry.dependencies]
python = "^3.7"
grunnlag = "^0.4.19"
napari = "^0.4.8"
qasync = "^0.13.0"

[tool.poetry.scripts]
napari-arnheim = "napari_arnheim.run:main"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
