
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-07T14:48:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2f8acd176e373050db1329c16aef4a4ababa90c",
 "version": "2021.06.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
