[tool.poetry]
name = "arcane-dataflow"
version = "0.1.0"
description = "Helpers for google dataflow services"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
google-api-python-client = "1.7.8"
oauth2client = "4.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
