from collections import namedtuple
from quickbuild.endpoints import Audits as Audits, Builds as Builds, Configurations as Configurations, Groups as Groups, Requests as Requests, System as System, Tokens as Tokens, Users as Users
from quickbuild.exceptions import QBError as QBError, QBForbiddenError as QBForbiddenError, QBNotFoundError as QBNotFoundError, QBProcessingError as QBProcessingError
from typing import Any

Response = namedtuple('Response', ['status', 'headers', 'body'])

class QuickBuild:
    audits: Any = ...
    builds: Any = ...
    configurations: Any = ...
    groups: Any = ...
    requests: Any = ...
    system: Any = ...
    tokens: Any = ...
    users: Any = ...
    def __init__(self) -> None: ...
