[tool.poetry]
name = "jbtuner-manager"
version = "0.1.1"
description = ""
authors = ["Ying Shaodong <gavin.ying@chordx.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.7,<4.0"
typer = {extras = ["all"], version = "^0.3.2"}
adafruit-ampy = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = true
log_level = "DEBUG"

[tool.poetry.scripts]
jbtman = "jbtuner_manager.main:app"
