name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:

  - python=3.8
  - xarray
  - xgcm
  - cftime
  - regionmask
  - pyproj
  - matplotlib
  # Dependencies for the pangeo cloud data
  - intake-esm
  - gcsfs
  - zarr
  # Dependencies for the testing suite
  - pytest-cov
  - pytest-xdist
  - pytest-rerunfailures
  - codecov
