[tool.black]
line-length = 130
target_version = ["py38"]
include = '''
(
    ^/tests/.*[.]py$
  | ^/mb_commons/.*[.]py$
  | ^/setup[.]py
)
'''
exclude = '''
(
     __pycache__
     | .venv
)
'''


[tool.isort]
line_length = 130
use_parentheses = "True"
include_trailing_comma = "True"
multi_line_output = 3
default_section = "THIRDPARTY"
known_first_party = "mb_commons"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
