[tool.poetry]
name = "textual"
version = "0.1.0"
description = "Text User Interface using Rich"
authors = ["Will McGugan <willmcgugan@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
rich = "^10.2.2"

[tool.poetry.dev-dependencies]
rich = {git = "git@github.com:willmcgugan/rich", rev = "tui"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
