[tool.poetry]
name = "pydispix"
version = "1.2.1"
authors = ["ItsDrike <itsdrikeofficial@gmail.com>"]
description = "API wrapper for python-discord's pixels."
readme = "README.md"
repository = "https://github.com/ItsDrike/pydispix"
license = "MIT"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
packages = [
    { include = "pydispix" }
]

[tool.poetry.dependencies]
python = "3.8.*"
requests = "~=2.25.1"
pillow = "~=8.2.0"
matplotlib = "~=3.4.2"
colorama = "~=0.4.4"

[tool.poetry.dev-dependencies]
autopep8 = "~=1.5.7"
flake8 = "~=3.9.2"
flake8-bugbear = "~=21.4.3"
flake8-import-order = "~=0.18.1"
ipython = "~=7.24.0"
pre-commit = "~=2.13.0"
taskipy = "~=1.8.1"
pep8-naming = "~=0.11.1"
flake8-tidy-imports = "~=4.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
