
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T19:57:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4ac89c6c95b1c2905d3cbf65b2cffa8eb582209",
 "version": "2021.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
