[tool.poetry]
name = "simsapa"
version = "0.1.6"
description = "Simsapa Dhamma Reader"
authors = ["Gambhiro <gambhiro.bhikkhu.85@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "==5.15.0"
SQLAlchemy = "^1.4.6"
Markdown = "^3.3.4"
PyYAML = "^5.4.1"
SQLAlchemy-Utils = "^0.37.2"
requests = "^2.25.1"
appdirs = "^1.4.4"
PyPDF2 = "^1.26.0"
epub_meta = "^0.0.7"

PyMuPDF = [
  { version =  "^1.18.13", markers = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { version =  "^1.18.13", platform = "win32" },
  { version =  "^1.18.13", platform = "darwin" },
]
pandas = "^1.2.4"
openpyxl = "^3.0.7"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}