[tool.black]
line-length = 120
target-version = ['py38']
include = '\pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | build
  | dist
  | \.local
  | \.cache
  | cache
)/
'''
