
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-04T08:47:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b472f5aa19a85eb56622d362d3bde0373eadc68",
 "version": "4.3.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
