[tool.poetry]
name = "django-qiyu-token"
version = "0.1.0"
description = ""
authors = ["dev <dev@qiyutech.tech>"]

[tool.poetry.dependencies]
python = "^3.9"

django = ">=3.2,<3.3"

[tool.poetry.dev-dependencies]
black = "*"
pytest = "*"
pytest-django = "*"
pylama = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
