locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: first_name
    locators:
      - mode: id
        value: RESULT_TextField-0
        index: 0
        uses: 99
  - verb: fill
    name: last_name
    locators:
      - mode: id
        value: RESULT_TextField-1
        index: 0
        uses: 99
  - verb: fill
    name: email_address
    locators:
      - mode: id
        value: RESULT_TextField-2
        index: 0
        uses: 99
  - verb: fill
    name: phone_number
    locators:
      - mode: id
        value: RESULT_TextField-3
        index: 0
        uses: 99
  - verb: select
    name: state
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: state
        index: 0
        uses: -1
      - mode: name
        value: state
        index: 0
        uses: -1
      - mode: id
        value: state
        index: 0
        uses: -1
      - mode: id
        value: state
        index: 0
        uses: -1
      - mode: aria-label
        value: State
        index: 0
        uses: -1
      - mode: css
        value: '[placeholder="State"]'
        index: 0
        uses: -1
      - mode: id
        value: State
        index: 0
        uses: -1
      - mode: id
        value: RESULT_RadioButton-4
        index: 0
        uses: -1
  - verb: fill
    name: zip_code
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: zip_code
        index: 0
        uses: -1
      - mode: name
        value: zip-code
        index: 0
        uses: -1
      - mode: id
        value: zip_code
        index: 0
        uses: -1
      - mode: id
        value: zip-code
        index: 0
        uses: -1
      - mode: aria-label
        value: Zip Code
        index: 0
        uses: -1
      - mode: css
        value: '[placeholder="Zip Code"]'
        index: 0
        uses: -1
      - mode: id
        value: ZipCode
        index: 0
        uses: -1
      - mode: id
        value: RESULT_TextField-5
        index: 0
        uses: 95
  - verb: click
    name: phone
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Phone
        index: 0
        uses: 95
      - mode: text
        value: Phone
        index: 0
        uses: 0
      - mode: text
        value: phone
        index: 0
        uses: 0
      - mode: value
        value: Phone
        index: 0
        uses: 0
      - mode: value
        value: Phone
        index: 0
        uses: 0
      - mode: value
        value: phone
        index: 0
        uses: 0
  - verb: click
    name: sponsorships
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Sponsorships
        index: 0
        uses: 95
      - mode: text
        value: Sponsorships
        index: 0
        uses: 0
      - mode: text
        value: sponsorships
        index: 0
        uses: 0
      - mode: value
        value: Sponsorships
        index: 0
        uses: 0
      - mode: value
        value: Sponsorships
        index: 0
        uses: 0
      - mode: value
        value: sponsorships
        index: 0
        uses: 0
  - verb: fill
    name: message
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: message
        index: 0
        uses: -1
      - mode: name
        value: message
        index: 0
        uses: -1
      - mode: id
        value: message
        index: 0
        uses: -1
      - mode: id
        value: message
        index: 0
        uses: -1
      - mode: aria-label
        value: Message
        index: 0
        uses: -1
      - mode: css
        value: '[placeholder="Message"]'
        index: 0
        uses: -1
      - mode: id
        value: Message
        index: 0
        uses: -1
      - mode: id
        value: RESULT_TextArea-13
        index: 0
        uses: 90
  - verb: click
    name: submit
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Submit
        index: 0
        uses: -1
      - mode: text
        value: Submit
        index: 0
        uses: -1
      - mode: text
        value: submit
        index: 0
        uses: -1
      - mode: value
        value: Submit
        index: 0
        uses: -1
      - mode: value
        value: Submit
        index: 0
        uses: -1
      - mode: value
        value: submit
        index: 0
        uses: -1
  - verb: click
    name: state
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: State
        index: 0
        uses: -1
      - mode: text
        value: State
        index: 0
        uses: -1
      - mode: text
        value: state
        index: 0
        uses: -1
      - mode: value
        value: State
        index: 0
        uses: -1
      - mode: value
        value: State
        index: 0
        uses: -1
      - mode: value
        value: state
        index: 0
        uses: -1
      - mode: id
        value: RESULT_RadioButton-4
        index: 0
        uses: 94
