[tool.poetry]
name = "disclist"
version = "0.0.1"
authors = ["proguy914629"]
readme = "README.md"
description = "A simple asynchronous/synchronous wrapper for https://disclist.noxitb.repl.co/ Bot List."
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.5"
aiohttp = "^3.7.4"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"