
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-01T23:57:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a795194c17e976f3c8cbf68e9d3d105fbd8acf7",
 "version": "0.1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
