name: Tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    env:
      INEGI_TOKEN: ${{ secrets.INEGI_TOKEN }}
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag clean_enoa .
    - name: Verifica el formato
      run: docker run clean_enoa make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run --env "INEGI_TOKEN=${INEGI_TOKEN}" clean_enoa make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run --env "INEGI_TOKEN=${INEGI_TOKEN}" clean_enoa make mutants
