# Generated by Django 3.1 on 2020-12-07 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_supervisor_plugin', '0006_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='sid',
            field=models.CharField(max_length=8, unique=False),
        ),
    ]
