
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-03T03:54:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2141464fec5f4966f3edbb359d0ef40141a8213f",
 "version": "2.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
