from asset_id import roasset
from creator import robloxasset
from creator_id import robloxasset
from is_public import robloxasset
from product_id import robloxasset
from name import robloxasset
from description import robloxasset
from asset_type_id import robloxasset
from created_at import robloxasset
from last_updated import robloxasset
from price_in_robux import robloxasset
from sales import robloxasset
from is_new import robloxasset
from is_for_sale import robloxasset
from is_limited import robloxasset
from remaining import robloxasset
from thumbnail import robloxasset
from assetloc import robloxasset