[tool.poetry]
name = "pandas-downcast"
version = "0.1.0.dev1"
description = "Automated downcasting for Pandas DataFrames."
authors = ["Dominic Thorn <dominic.thorn@gmail.com>"]
license = "MIT"
packages = [
    {include = "pdcast"}
]

[tool.poetry.dependencies]
python = ">=3.6.2,<4"
pandas = ">=0.24"
numpy = ">=1.16.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.812"
flake8 = "^3.9.2"
black = "^21.5b2"
pandas-stubs = "^1.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
