[package]
name = "scalib"
version = "0.1.0"
authors = ["obronchain <olivier.bronchain@uclouvain.be>"]
edition = "2018"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[features]
blis = ["blis-src", "blis-sys"]

[dependencies]
numpy = "0.13.0"
rayon = "1.5.0"
num-integer = "0.1.42"
indicatif = "0.16.0"
ndarray = { version = "0.15.1", features = ["rayon", "approx"] }
itertools = "0.10.0"
ndarray-stats = "0.5.0"
lapacke = "0.3.0"
lazy_static = "1.4.0"
nalgebra = "0.26.1"
approx = "0.4.0"
geigen = { path = "../geigen" }
nshare = { git= "https://github.com/cassiersg/nshare", branch="rm_lt", features=["nalgebra", "ndarray", "std"] }
blis-src = { version = "0.2.1-alpha.0", default-features=false, features=["static", "pthreads"], optional = true }
blis-sys = { git="https://github.com/cassiersg/blis-sys", optional = true }
matrixmultiply = "0.3.1"

[dev-dependencies]
criterion = "0.3"
ndarray-rand = "0.14.0"

[[bench]]
name = "belief_propagation"
harness = false

[[bench]]
name = "lda"
harness = false

[[bench]]
name = "lda_ntraces"
harness = false

[[bench]]
name = "get_snr"
harness = false
