[tool.poetry]
name = "stupid"
version = "1.1.1"
description = "A stupid workaround when using multiple inheritance and __slots__"
authors = ["masell"]
readme = "README.md"
homepage = 'https://github.com/masell/stupid'
repository = 'https://github.com/masell/stupid'
license = "BSD-2-Clause"
classifiers=[
    'Development Status :: 4 - Beta',
    "License :: OSI Approved :: BSD License",
    'Programming Language :: Python :: 3.7',
    'Intended Audience :: Developers',
    'Operating System :: OS Independent',
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
