[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "mangadex_openapi"
author = "Ong Yong Xin"
author-email = "ongyongxin2020+github@gmail.com"
home-page = "https://github.com/ongyx/mangadex_openapi"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
description-file = "README.md"
requires = [
    "certifi>=14.05.14",
    "six>=1.10",
    "python-dateutil>=2.5.3",
    "urllib3>=1.15.1",
]
requires-python = ">=3.6"

[tool.flit.metadata.requires-extra]
test = [
    "pytest>=6.2.2"
]
docs = [
    "pydoc-markdown>=3.10.1",
    "black>=21.5b1"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rP"
