#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mangadex_openapi',
 'mangadex_openapi.api',
 'mangadex_openapi.models',
 'mangadex_openapi.wrapper',
 'mangadex_openapi.wrapper.iso639']

package_data = \
{'': ['*']}

install_requires = \
['certifi>=14.05.14', 'six>=1.10', 'python-dateutil>=2.5.3', 'urllib3>=1.15.1']

extras_require = \
{'docs': ['pydoc-markdown>=3.10.1', 'black>=21.5b1'], 'test': ['pytest>=6.2.2']}

setup(name='mangadex_openapi',
      version='0.4.0',
      description='MangaDex API',
      author='Ong Yong Xin',
      author_email='ongyongxin2020+github@gmail.com',
      url='https://github.com/ongyx/mangadex_openapi',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
