name: nr.preconditions
version: 0.0.4
author: Niklas Rosenstein <nrosenstein@palantir.com>
description: Provides simple functions to assert the state of your program.
requirements:
- python ^3.5
typed: true
