[build-system]
requires = ['flit_core >=2,<4']
build-backend = 'flit_core.buildapi'

[tool.flit.metadata]
module = 'bapy'
author = 'José'
classifiers = [ 'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',]
description-file = 'README.md'
requires = [
    'decorator',
    'environs',
    'furl',
    'marshmallow',
    'more_itertools',
    'nested_lookup',
    'requests[security]',
    'rich',
    'typer'
]

[tool.flit.scripts]
localbin = 'bapy:localbin'
bapy = 'bapy.main:app'
