name: Synreg easy
group: Synreg
task: regression
domain: synthetic
adapter:
  _target_: sklearn.datasets.make_regression
  n_samples: 10000
  n_features: 10
  n_informative: 2
  n_targets: 1
  bias: 200
  effective_rank: null
  noise: 0
  coef: False
  random_state: 0
feature_importances:
  X[:, :]: [0.0, 0.0, 0.0, 0.5398622871951788, 0.0, 0.0, 0.4601377128048212, 0.0, 0.0, 0.0]