# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programl/proto/epoch.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='programl/proto/epoch.proto',
  package='programl',
  syntax='proto3',
  serialized_options=b'\n\014com.programlB\nEpochProtoP\001Z\nprogramlpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aprograml/proto/epoch.proto\x12\x08programl\"\xdd\x02\n\x0c\x45pochResults\x12\x13\n\x0bgraph_count\x18\x01 \x01(\x03\x12\x13\n\x0b\x62\x61tch_count\x18\x02 \x01(\x03\x12\x14\n\x0ctarget_count\x18\x03 \x01(\x03\x12\x1c\n\x14mean_iteration_count\x18\x04 \x01(\x02\x12\x1c\n\x14mean_model_converged\x18\x05 \x01(\x02\x12\x1a\n\x12mean_learning_rate\x18\x06 \x01(\x02\x12\x11\n\tmean_loss\x18\x07 \x01(\x02\x12\x15\n\rmean_accuracy\x18\x08 \x01(\x02\x12\x16\n\x0emean_precision\x18\t \x01(\x02\x12\x13\n\x0bmean_recall\x18\n \x01(\x02\x12\x0f\n\x07mean_f1\x18\x0b \x01(\x02\x12\x33\n\x10\x63onfusion_matrix\x18\r \x01(\x0b\x32\x19.programl.ConfusionMatrix\x12\x18\n\x10walltime_seconds\x18\x0c \x01(\x02\"\xbe\x01\n\x05\x45poch\x12\x11\n\tepoch_num\x18\x01 \x01(\x05\x12\x18\n\x10walltime_seconds\x18\x05 \x01(\x02\x12-\n\rtrain_results\x18\x02 \x01(\x0b\x32\x16.programl.EpochResults\x12+\n\x0bval_results\x18\x03 \x01(\x0b\x32\x16.programl.EpochResults\x12,\n\x0ctest_results\x18\x04 \x01(\x0b\x32\x16.programl.EpochResults\"+\n\tEpochList\x12\x1e\n\x05\x65poch\x18\x01 \x03(\x0b\x32\x0f.programl.Epoch\"?\n\x0f\x43onfusionMatrix\x12,\n\x06\x63olumn\x18\x01 \x03(\x0b\x32\x1c.programl.ConfusionMatrixRow\"!\n\x12\x43onfusionMatrixRow\x12\x0b\n\x03row\x18\x02 \x03(\x03*)\n\tEpochType\x12\t\n\x05TRAIN\x10\x00\x12\x07\n\x03VAL\x10\x01\x12\x08\n\x04TEST\x10\x02\x42(\n\x0c\x63om.programlB\nEpochProtoP\x01Z\nprogramlpbb\x06proto3'
)

_EPOCHTYPE = _descriptor.EnumDescriptor(
  name='EpochType',
  full_name='programl.EpochType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAIN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TEST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=730,
  serialized_end=771,
)
_sym_db.RegisterEnumDescriptor(_EPOCHTYPE)

EpochType = enum_type_wrapper.EnumTypeWrapper(_EPOCHTYPE)
TRAIN = 0
VAL = 1
TEST = 2



_EPOCHRESULTS = _descriptor.Descriptor(
  name='EpochResults',
  full_name='programl.EpochResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph_count', full_name='programl.EpochResults.graph_count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_count', full_name='programl.EpochResults.batch_count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_count', full_name='programl.EpochResults.target_count', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_iteration_count', full_name='programl.EpochResults.mean_iteration_count', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_model_converged', full_name='programl.EpochResults.mean_model_converged', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_learning_rate', full_name='programl.EpochResults.mean_learning_rate', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_loss', full_name='programl.EpochResults.mean_loss', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_accuracy', full_name='programl.EpochResults.mean_accuracy', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_precision', full_name='programl.EpochResults.mean_precision', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_recall', full_name='programl.EpochResults.mean_recall', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_f1', full_name='programl.EpochResults.mean_f1', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confusion_matrix', full_name='programl.EpochResults.confusion_matrix', index=11,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='walltime_seconds', full_name='programl.EpochResults.walltime_seconds', index=12,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=390,
)


_EPOCH = _descriptor.Descriptor(
  name='Epoch',
  full_name='programl.Epoch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch_num', full_name='programl.Epoch.epoch_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='walltime_seconds', full_name='programl.Epoch.walltime_seconds', index=1,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_results', full_name='programl.Epoch.train_results', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val_results', full_name='programl.Epoch.val_results', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_results', full_name='programl.Epoch.test_results', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=583,
)


_EPOCHLIST = _descriptor.Descriptor(
  name='EpochList',
  full_name='programl.EpochList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='programl.EpochList.epoch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=628,
)


_CONFUSIONMATRIX = _descriptor.Descriptor(
  name='ConfusionMatrix',
  full_name='programl.ConfusionMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='programl.ConfusionMatrix.column', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=693,
)


_CONFUSIONMATRIXROW = _descriptor.Descriptor(
  name='ConfusionMatrixRow',
  full_name='programl.ConfusionMatrixRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='programl.ConfusionMatrixRow.row', index=0,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=728,
)

_EPOCHRESULTS.fields_by_name['confusion_matrix'].message_type = _CONFUSIONMATRIX
_EPOCH.fields_by_name['train_results'].message_type = _EPOCHRESULTS
_EPOCH.fields_by_name['val_results'].message_type = _EPOCHRESULTS
_EPOCH.fields_by_name['test_results'].message_type = _EPOCHRESULTS
_EPOCHLIST.fields_by_name['epoch'].message_type = _EPOCH
_CONFUSIONMATRIX.fields_by_name['column'].message_type = _CONFUSIONMATRIXROW
DESCRIPTOR.message_types_by_name['EpochResults'] = _EPOCHRESULTS
DESCRIPTOR.message_types_by_name['Epoch'] = _EPOCH
DESCRIPTOR.message_types_by_name['EpochList'] = _EPOCHLIST
DESCRIPTOR.message_types_by_name['ConfusionMatrix'] = _CONFUSIONMATRIX
DESCRIPTOR.message_types_by_name['ConfusionMatrixRow'] = _CONFUSIONMATRIXROW
DESCRIPTOR.enum_types_by_name['EpochType'] = _EPOCHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EpochResults = _reflection.GeneratedProtocolMessageType('EpochResults', (_message.Message,), {
  'DESCRIPTOR' : _EPOCHRESULTS,
  '__module__' : 'programl.proto.epoch_pb2'
  # @@protoc_insertion_point(class_scope:programl.EpochResults)
  })
_sym_db.RegisterMessage(EpochResults)

Epoch = _reflection.GeneratedProtocolMessageType('Epoch', (_message.Message,), {
  'DESCRIPTOR' : _EPOCH,
  '__module__' : 'programl.proto.epoch_pb2'
  # @@protoc_insertion_point(class_scope:programl.Epoch)
  })
_sym_db.RegisterMessage(Epoch)

EpochList = _reflection.GeneratedProtocolMessageType('EpochList', (_message.Message,), {
  'DESCRIPTOR' : _EPOCHLIST,
  '__module__' : 'programl.proto.epoch_pb2'
  # @@protoc_insertion_point(class_scope:programl.EpochList)
  })
_sym_db.RegisterMessage(EpochList)

ConfusionMatrix = _reflection.GeneratedProtocolMessageType('ConfusionMatrix', (_message.Message,), {
  'DESCRIPTOR' : _CONFUSIONMATRIX,
  '__module__' : 'programl.proto.epoch_pb2'
  # @@protoc_insertion_point(class_scope:programl.ConfusionMatrix)
  })
_sym_db.RegisterMessage(ConfusionMatrix)

ConfusionMatrixRow = _reflection.GeneratedProtocolMessageType('ConfusionMatrixRow', (_message.Message,), {
  'DESCRIPTOR' : _CONFUSIONMATRIXROW,
  '__module__' : 'programl.proto.epoch_pb2'
  # @@protoc_insertion_point(class_scope:programl.ConfusionMatrixRow)
  })
_sym_db.RegisterMessage(ConfusionMatrixRow)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
