[tool.poetry]
name = "airflow-test-decorator"
version = "1.1"
description = ""
authors = ["komalkot <komalkot@thoughtworks.com>",  "charanstw <charans@thoughtworks.com>"]

[tool.poetry.dependencies]
python = "^3.6"
presto-python-client = "^0.7.0"
SQLAlchemy = "~1.3"
cattrs = "1.0.0"
apache-airflow = "1.10.15"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.17.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
