# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithm_id.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='algorithm_id.proto',
  package='bayesmix',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x61lgorithm_id.proto\x12\x08\x62\x61yesmix*r\n\x0b\x41lgorithmId\x12\x15\n\x11UNKNOWN_ALGORITHM\x10\x00\x12\t\n\x05Neal2\x10\x01\x12\t\n\x05Neal3\x10\x02\x12\t\n\x05Neal8\x10\x03\x12\x10\n\x0c\x42lockedGibbs\x10\x04\x12\x0e\n\nSplitMerge\x10\x05\x12\t\n\x05Slice\x10\x06\x62\x06proto3'
)

_ALGORITHMID = _descriptor.EnumDescriptor(
  name='AlgorithmId',
  full_name='bayesmix.AlgorithmId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ALGORITHM', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Neal2', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Neal3', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Neal8', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BlockedGibbs', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SplitMerge', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Slice', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_ALGORITHMID)

AlgorithmId = enum_type_wrapper.EnumTypeWrapper(_ALGORITHMID)
UNKNOWN_ALGORITHM = 0
Neal2 = 1
Neal3 = 2
Neal8 = 3
BlockedGibbs = 4
SplitMerge = 5
Slice = 6


DESCRIPTOR.enum_types_by_name['AlgorithmId'] = _ALGORITHMID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
