# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: semihdp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ls_state_pb2 as ls__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='semihdp.proto',
  package='bayesmix',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsemihdp.proto\x12\x08\x62\x61yesmix\x1a\x0els_state.proto\"\xc7\x04\n\x0cSemiHdpState\x12;\n\x0brestaurants\x18\x01 \x03(\x0b\x32&.bayesmix.SemiHdpState.RestaurantState\x12\x31\n\x06groups\x18\x02 \x03(\x0b\x32!.bayesmix.SemiHdpState.GroupState\x12\x31\n\x04taus\x18\x03 \x03(\x0b\x32#.bayesmix.SemiHdpState.ClusterState\x12\t\n\x01\x63\x18\x04 \x03(\x05\x12\t\n\x01w\x18\x05 \x01(\x01\x1a\xc6\x01\n\x0c\x43lusterState\x12,\n\x0cuni_ls_state\x18\x01 \x01(\x0b\x32\x14.bayesmix.UniLSStateH\x00\x12\x30\n\x0emulti_ls_state\x18\x02 \x01(\x0b\x32\x16.bayesmix.MultiLSStateH\x00\x12:\n\x14lin_reg_uni_ls_state\x18\x04 \x01(\x0b\x32\x1a.bayesmix.LinRegUniLSStateH\x00\x12\x13\n\x0b\x63\x61rdinality\x18\x03 \x01(\x05\x42\x05\n\x03val\x1a\x8e\x01\n\x0fRestaurantState\x12\x38\n\x0btheta_stars\x18\x01 \x03(\x0b\x32#.bayesmix.SemiHdpState.ClusterState\x12\x11\n\tn_by_clus\x18\x02 \x03(\x05\x12\x17\n\x0ftable_to_shared\x18\x03 \x03(\x05\x12\x15\n\rtable_to_idio\x18\x04 \x03(\x05\x1a$\n\nGroupState\x12\x16\n\x0e\x63luster_allocs\x18\x01 \x03(\x05\"\x80\x03\n\rSemiHdpParams\x12?\n\x0cpseudo_prior\x18\x01 \x01(\x0b\x32).bayesmix.SemiHdpParams.PseudoPriorParams\x12\x1f\n\x17\x64irichlet_concentration\x18\x02 \x01(\x01\x12\x1a\n\x12rest_allocs_update\x18\x03 \x01(\t\x12\x16\n\x0etotalmass_rest\x18\x04 \x01(\x01\x12\x15\n\rtotalmass_hdp\x18\x05 \x01(\x01\x12\x35\n\x07w_prior\x18\x06 \x01(\x0b\x32$.bayesmix.SemiHdpParams.WPriorParams\x1a[\n\x11PseudoPriorParams\x12\x13\n\x0b\x63\x61rd_weight\x18\x01 \x01(\x01\x12\x17\n\x0fmean_perturb_sd\x18\x02 \x01(\x01\x12\x18\n\x10var_perturb_frac\x18\x03 \x01(\x01\x1a.\n\x0cWPriorParams\x12\x0e\n\x06shape1\x18\x01 \x01(\x01\x12\x0e\n\x06shape2\x18\x02 \x01(\x01\x62\x06proto3'
  ,
  dependencies=[ls__state__pb2.DESCRIPTOR,])




_SEMIHDPSTATE_CLUSTERSTATE = _descriptor.Descriptor(
  name='ClusterState',
  full_name='bayesmix.SemiHdpState.ClusterState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uni_ls_state', full_name='bayesmix.SemiHdpState.ClusterState.uni_ls_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multi_ls_state', full_name='bayesmix.SemiHdpState.ClusterState.multi_ls_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lin_reg_uni_ls_state', full_name='bayesmix.SemiHdpState.ClusterState.lin_reg_uni_ls_state', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cardinality', full_name='bayesmix.SemiHdpState.ClusterState.cardinality', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='val', full_name='bayesmix.SemiHdpState.ClusterState.val',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=246,
  serialized_end=444,
)

_SEMIHDPSTATE_RESTAURANTSTATE = _descriptor.Descriptor(
  name='RestaurantState',
  full_name='bayesmix.SemiHdpState.RestaurantState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta_stars', full_name='bayesmix.SemiHdpState.RestaurantState.theta_stars', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_by_clus', full_name='bayesmix.SemiHdpState.RestaurantState.n_by_clus', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table_to_shared', full_name='bayesmix.SemiHdpState.RestaurantState.table_to_shared', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table_to_idio', full_name='bayesmix.SemiHdpState.RestaurantState.table_to_idio', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=589,
)

_SEMIHDPSTATE_GROUPSTATE = _descriptor.Descriptor(
  name='GroupState',
  full_name='bayesmix.SemiHdpState.GroupState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_allocs', full_name='bayesmix.SemiHdpState.GroupState.cluster_allocs', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=627,
)

_SEMIHDPSTATE = _descriptor.Descriptor(
  name='SemiHdpState',
  full_name='bayesmix.SemiHdpState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='restaurants', full_name='bayesmix.SemiHdpState.restaurants', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='groups', full_name='bayesmix.SemiHdpState.groups', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taus', full_name='bayesmix.SemiHdpState.taus', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c', full_name='bayesmix.SemiHdpState.c', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='bayesmix.SemiHdpState.w', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SEMIHDPSTATE_CLUSTERSTATE, _SEMIHDPSTATE_RESTAURANTSTATE, _SEMIHDPSTATE_GROUPSTATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=627,
)


_SEMIHDPPARAMS_PSEUDOPRIORPARAMS = _descriptor.Descriptor(
  name='PseudoPriorParams',
  full_name='bayesmix.SemiHdpParams.PseudoPriorParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_weight', full_name='bayesmix.SemiHdpParams.PseudoPriorParams.card_weight', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_perturb_sd', full_name='bayesmix.SemiHdpParams.PseudoPriorParams.mean_perturb_sd', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='var_perturb_frac', full_name='bayesmix.SemiHdpParams.PseudoPriorParams.var_perturb_frac', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=875,
  serialized_end=966,
)

_SEMIHDPPARAMS_WPRIORPARAMS = _descriptor.Descriptor(
  name='WPriorParams',
  full_name='bayesmix.SemiHdpParams.WPriorParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape1', full_name='bayesmix.SemiHdpParams.WPriorParams.shape1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape2', full_name='bayesmix.SemiHdpParams.WPriorParams.shape2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=968,
  serialized_end=1014,
)

_SEMIHDPPARAMS = _descriptor.Descriptor(
  name='SemiHdpParams',
  full_name='bayesmix.SemiHdpParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pseudo_prior', full_name='bayesmix.SemiHdpParams.pseudo_prior', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dirichlet_concentration', full_name='bayesmix.SemiHdpParams.dirichlet_concentration', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rest_allocs_update', full_name='bayesmix.SemiHdpParams.rest_allocs_update', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalmass_rest', full_name='bayesmix.SemiHdpParams.totalmass_rest', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalmass_hdp', full_name='bayesmix.SemiHdpParams.totalmass_hdp', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w_prior', full_name='bayesmix.SemiHdpParams.w_prior', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SEMIHDPPARAMS_PSEUDOPRIORPARAMS, _SEMIHDPPARAMS_WPRIORPARAMS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=1014,
)

_SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['uni_ls_state'].message_type = ls__state__pb2._UNILSSTATE
_SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['multi_ls_state'].message_type = ls__state__pb2._MULTILSSTATE
_SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['lin_reg_uni_ls_state'].message_type = ls__state__pb2._LINREGUNILSSTATE
_SEMIHDPSTATE_CLUSTERSTATE.containing_type = _SEMIHDPSTATE
_SEMIHDPSTATE_CLUSTERSTATE.oneofs_by_name['val'].fields.append(
  _SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['uni_ls_state'])
_SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['uni_ls_state'].containing_oneof = _SEMIHDPSTATE_CLUSTERSTATE.oneofs_by_name['val']
_SEMIHDPSTATE_CLUSTERSTATE.oneofs_by_name['val'].fields.append(
  _SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['multi_ls_state'])
_SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['multi_ls_state'].containing_oneof = _SEMIHDPSTATE_CLUSTERSTATE.oneofs_by_name['val']
_SEMIHDPSTATE_CLUSTERSTATE.oneofs_by_name['val'].fields.append(
  _SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['lin_reg_uni_ls_state'])
_SEMIHDPSTATE_CLUSTERSTATE.fields_by_name['lin_reg_uni_ls_state'].containing_oneof = _SEMIHDPSTATE_CLUSTERSTATE.oneofs_by_name['val']
_SEMIHDPSTATE_RESTAURANTSTATE.fields_by_name['theta_stars'].message_type = _SEMIHDPSTATE_CLUSTERSTATE
_SEMIHDPSTATE_RESTAURANTSTATE.containing_type = _SEMIHDPSTATE
_SEMIHDPSTATE_GROUPSTATE.containing_type = _SEMIHDPSTATE
_SEMIHDPSTATE.fields_by_name['restaurants'].message_type = _SEMIHDPSTATE_RESTAURANTSTATE
_SEMIHDPSTATE.fields_by_name['groups'].message_type = _SEMIHDPSTATE_GROUPSTATE
_SEMIHDPSTATE.fields_by_name['taus'].message_type = _SEMIHDPSTATE_CLUSTERSTATE
_SEMIHDPPARAMS_PSEUDOPRIORPARAMS.containing_type = _SEMIHDPPARAMS
_SEMIHDPPARAMS_WPRIORPARAMS.containing_type = _SEMIHDPPARAMS
_SEMIHDPPARAMS.fields_by_name['pseudo_prior'].message_type = _SEMIHDPPARAMS_PSEUDOPRIORPARAMS
_SEMIHDPPARAMS.fields_by_name['w_prior'].message_type = _SEMIHDPPARAMS_WPRIORPARAMS
DESCRIPTOR.message_types_by_name['SemiHdpState'] = _SEMIHDPSTATE
DESCRIPTOR.message_types_by_name['SemiHdpParams'] = _SEMIHDPPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SemiHdpState = _reflection.GeneratedProtocolMessageType('SemiHdpState', (_message.Message,), {

  'ClusterState' : _reflection.GeneratedProtocolMessageType('ClusterState', (_message.Message,), {
    'DESCRIPTOR' : _SEMIHDPSTATE_CLUSTERSTATE,
    '__module__' : 'semihdp_pb2'
    # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpState.ClusterState)
    })
  ,

  'RestaurantState' : _reflection.GeneratedProtocolMessageType('RestaurantState', (_message.Message,), {
    'DESCRIPTOR' : _SEMIHDPSTATE_RESTAURANTSTATE,
    '__module__' : 'semihdp_pb2'
    # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpState.RestaurantState)
    })
  ,

  'GroupState' : _reflection.GeneratedProtocolMessageType('GroupState', (_message.Message,), {
    'DESCRIPTOR' : _SEMIHDPSTATE_GROUPSTATE,
    '__module__' : 'semihdp_pb2'
    # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpState.GroupState)
    })
  ,
  'DESCRIPTOR' : _SEMIHDPSTATE,
  '__module__' : 'semihdp_pb2'
  # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpState)
  })
_sym_db.RegisterMessage(SemiHdpState)
_sym_db.RegisterMessage(SemiHdpState.ClusterState)
_sym_db.RegisterMessage(SemiHdpState.RestaurantState)
_sym_db.RegisterMessage(SemiHdpState.GroupState)

SemiHdpParams = _reflection.GeneratedProtocolMessageType('SemiHdpParams', (_message.Message,), {

  'PseudoPriorParams' : _reflection.GeneratedProtocolMessageType('PseudoPriorParams', (_message.Message,), {
    'DESCRIPTOR' : _SEMIHDPPARAMS_PSEUDOPRIORPARAMS,
    '__module__' : 'semihdp_pb2'
    # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpParams.PseudoPriorParams)
    })
  ,

  'WPriorParams' : _reflection.GeneratedProtocolMessageType('WPriorParams', (_message.Message,), {
    'DESCRIPTOR' : _SEMIHDPPARAMS_WPRIORPARAMS,
    '__module__' : 'semihdp_pb2'
    # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpParams.WPriorParams)
    })
  ,
  'DESCRIPTOR' : _SEMIHDPPARAMS,
  '__module__' : 'semihdp_pb2'
  # @@protoc_insertion_point(class_scope:bayesmix.SemiHdpParams)
  })
_sym_db.RegisterMessage(SemiHdpParams)
_sym_db.RegisterMessage(SemiHdpParams.PseudoPriorParams)
_sym_db.RegisterMessage(SemiHdpParams.WPriorParams)


# @@protoc_insertion_point(module_scope)
