[tool.poetry]
name = "seesv"
version = "0.1.2"
description = "A Python library providing fast access to data in very large delimited data files (CSV, TSV, pipe-delimited, etc)."
authors = ["David Alexis <dalexis@gmail.com>"]
keywords = ["csv", "delimited files"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/davealexis/pyseesv"
repository = "https://github.com/davealexis/pyseesv"
include = ["LICENSE"]


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
