[tool.poetry]
name = "pipecheck"
version = "0.1.1"
description = "This simple tool can be used to verify the state of a system's context."
authors = ["Michael Riedmann <michael_riedmann@live.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
certifi = "^2021.5.30"
icecream = "^2.1.0"
icmplib = "^3.0"
netaddr = "^0.8.0"
prometheus-client = "^0.11.0"
termcolor = "^1.1.0"
urllib3 = "^1.26.5"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
parameterized = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
