[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=0.13.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyspawner"
version = "1.0.0"
description = "Clone sandboxed Python processes quickly and securely, on Linux."
authors = ["Adam Hooper <adam@adamhooper.com>"]
license = "BSD"
readme = "README.rst"
homepage = "https://github.com/CJWorkbench/pyspawner"
repository = "https://github.com/CJWorkbench/pyspawner.git"

[tool.poetry.dependencies]
python = ">=3.7"
"pyroute2.minimal" = "~=0.6.4"

[tool.poetry.dev-dependencies]
pytest = "~=6.1"
pytest-cov = "~= 2.10"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.isort]
# Black compatibility
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
skipsdist = True
envlist = py{38,39}

[flake8]
exclude = venv/*,tox/*,specs/*,build/*
ignore = E123,E128,E266,E402,W503,E731,W601
max-line-length = 88

[testenv]
skip_install = true
deps =
  poetry
commands_pre =
  poetry install -v
commands =
  poetry run pytest --cov=pyspawner --cov-report term-missing -v
"""
