[tool.poetry]
name = "royston"
version = "0.0.9"
description = "A real time trend detection algorithm"
authors = ["Ian Read <ianharveyread@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-dateutil = "^2.8.1"
nltk = "^3.6.2"
dateparser = "^1.0.0"
pytz = "^2021.1"
gensim = "^4.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
