[tool.poetry]
name = "essencia_app"
version = "0.1.0"
description = "MIT"
authors = ["arantesdv <arantesdv@me.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
deta = "^0.8"
starlette = "^0.14.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
