# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['dict_to_str', 'say_hello', 'HelloSayer']

# Cell
def dict_to_str(d: dict, sep: str = '::') -> str:
    return sep.join(
        [str(k) + sep + str(v) for k, v in sorted(d.items())])

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        return say_hello(self.to)