
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-05T20:15:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d19faa073233d57f2f02ef229cf8cfe3e0a284d",
 "version": "2021.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
