[tool.poetry]
name = "jackutils"
version = "0.1.0"
description = "my own utils funcs and classes"
authors = ["Jack Li <lijack1@163.com>"]

packages = [
    { include="core", from="." },
]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
sympy = "^1.8"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
