
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-07T12:57:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "96e4c9d699de3dbcbe26c19a901680127b604a16",
 "version": "5.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
