#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['huispedia']

package_data = \
{'': ['*']}

install_requires = \
['requests']

extras_require = \
{'test': ['pytest']}

setup(name='huispedia',
      version='0.1.0',
      description='Get information about houses from huispedia.nl',
      author='Gram',
      author_email='gram@orsinium.dev',
      url='https://github.com/orsinium-labs/huispedia',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
