[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "gpx"
author = "Steven van de Graaf"
author-email = "steven@vandegraaf.xyz"
home-page = "https://github.com/sgraaf/PyGPX"
requires = [
    "lxml >= 4.6.3",
    "python-dateutil >= 2.8.1",
]
requires-python = ">=3.8"
description-file = "README.md"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
]

[tool.flit.metadata.requires-extra]
dev = [
    "black >= 20.8b1",
    "coverage >= 5.5",
    "flake8 >= 3.9.1",
    "flake8-bugbear >= 21.4.3",
    "flake8-docstrings >= 1.6.0",
    "mccabe >= 0.6.1",
    "mypy >= 0.812",
    "pytest >= 6.2.3",
    "tox >= 3.23.0",
]
