[tool.poetry]
name = "appmap"
version = "1.1.0"
description = "Create AppMap files by recording a Python application."
readme = "README.md"
authors = [
  "Alan Potter <alan@app.land>",
  "Viraj Kanwade <viraj.kanwade@forgeahead.io>",
  "Rafał Rzepecki <rafal@app.land>"
]
homepage = "https://github.com/applandinc/appmap-python"
license = "MIT"
classifiers = [
        'Development Status :: 4 - Beta',
        'Framework :: Django',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.1',
        'Framework :: Flask',
        'Framework :: Pytest',
        'Intended Audience :: Developers',
        'Topic :: Software Development',
        'Topic :: Software Development :: Debuggers',
        'Topic :: Software Development :: Documentation'
]
include = ['appmap.pth']

packages = [
    { include = "appmap" },
    { include = "appmap/wrapt/*.py", from="vendor/wrapt/src" }
]

[tool.poetry.dependencies]
python = "^3.6"
PyYAML = "~5.3.0"
inflection = "~0.3.0"
importlib-metadata = ">=0.8"

[tool.poetry.dev-dependencies]
httpretty = "^1.0.5"
pytest = "^6.1.2"
pytest-randomly = "^3.5.0"
pylint = "^2.6.0"
flake8 = "^3.8.4"
pyfakefs = "^4.3.2"
pprintpp = "^0.4.0"
coverage = "^5.3"
pytest-mock = "^3.5.1"
Django = { version = "^3.1.6", python = "^3.6", optional = true }
flask = "^1.1.2"
SQLAlchemy = { version = "^1.4.11", python = "^3.6"}
tox = "^3.22.0"
tox-pyenv = "^1.1.0"
tox-travis = "^0.12"
Twisted = "^21.2.0"
requests = "^2.25.1"

[tool.poetry.extras]
test = ["Django"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."pytest11"]
appmap = "appmap.pytest"
