name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgresql:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: heroku_connect_test
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Install package dependencies
      run: |
        sudo apt-get install -y gdal-bin

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

    - name: installing coveragepy for codecov upload
      # the codecov github action needs this package to find the reports
      run: pip install coverage

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
