
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T01:06:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ec88b75a8cf6d6a9c4ade6ac85a9b861688bdbd",
 "version": "0.7.0.post.dev154"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
