[tool.poetry]
name = "elz-py-tools"
version = "0.1.0"
description = "Python tools for Elzeard modules"
authors = ["Hervé <herve.descombe@elzeard.co>"]
license = "Apache v2"

[tool.poetry.dependencies]
python = "^3.8"
aio-pika = "^6.8.0"
pymongo = "^3.11.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
