# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programl/proto/ir.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='programl/proto/ir.proto',
  package='programl',
  syntax='proto3',
  serialized_options=b'\n\014com.programlB\007IrProtoP\001Z\nprogramlpb\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17programl/proto/ir.proto\x12\x08programl\"\x86\x01\n\x02Ir\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.programl.Ir.Type\x12\x18\n\x10\x63ompiler_version\x18\x02 \x01(\x03\x12\x0b\n\x03\x63md\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\"*\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04LLVM\x10\x01\x12\x0b\n\x07XLA_HLO\x10\x02\"\"\n\x06IrList\x12\x18\n\x02ir\x18\x01 \x03(\x0b\x32\x0c.programl.IrB(\n\x0c\x63om.programlB\x07IrProtoP\x01Z\nprogramlpb\xf8\x01\x01\x62\x06proto3'
)



_IR_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='programl.Ir.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LLVM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XLA_HLO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=130,
  serialized_end=172,
)
_sym_db.RegisterEnumDescriptor(_IR_TYPE)


_IR = _descriptor.Descriptor(
  name='Ir',
  full_name='programl.Ir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='programl.Ir.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compiler_version', full_name='programl.Ir.compiler_version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='programl.Ir.cmd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='programl.Ir.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IR_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=172,
)


_IRLIST = _descriptor.Descriptor(
  name='IrList',
  full_name='programl.IrList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ir', full_name='programl.IrList.ir', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=208,
)

_IR.fields_by_name['type'].enum_type = _IR_TYPE
_IR_TYPE.containing_type = _IR
_IRLIST.fields_by_name['ir'].message_type = _IR
DESCRIPTOR.message_types_by_name['Ir'] = _IR
DESCRIPTOR.message_types_by_name['IrList'] = _IRLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ir = _reflection.GeneratedProtocolMessageType('Ir', (_message.Message,), {
  'DESCRIPTOR' : _IR,
  '__module__' : 'programl.proto.ir_pb2'
  # @@protoc_insertion_point(class_scope:programl.Ir)
  })
_sym_db.RegisterMessage(Ir)

IrList = _reflection.GeneratedProtocolMessageType('IrList', (_message.Message,), {
  'DESCRIPTOR' : _IRLIST,
  '__module__' : 'programl.proto.ir_pb2'
  # @@protoc_insertion_point(class_scope:programl.IrList)
  })
_sym_db.RegisterMessage(IrList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
