__title__ = 'SECFE'
__description__ = 'A Python package for downloading and extracting information from SEC Filings. As a note, this package requires lxml functions that may not run on Mac OS. '
__url__ = 'https://github.com/arechiga-code/SECFE'
__github_url__ = 'https://github.com/arechiga-code/SECFE'
__version__ = '0.3.2'
__license__ = 'MIT'
