#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['py_edl_editor', 'py_edl_editor.test']

package_data = \
{'': ['*'], 'py_edl_editor.test': ['files/*']}

install_requires = \
['PySide2', 'cdl_convert', 'opentimelineio', 'timecode', 'edl']

entry_points = \
{'console_scripts': ['edl_editor = py_edl_editor.__main__:main']}

setup(name='py_edl_editor',
      version='0.2.0',
      description='``py_edl_editor`` Module',
      author='Thomas Weckenmann',
      author_email='tweckenmann0711@gmail.com',
      url='https://github.com/ThomasWeckenmann/py_edl_editor',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
