
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-01T21:03:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "269cc76ea313eba48d8c6badaf0a783550f48766",
 "version": "4.3.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
