[tool.poetry]
name = "inspy-logger"
version = "2.1a14"
description = "Colorable, scalable logger for CLI"
authors = ["Taylor-Jayde Blackstone <tayjaybabee@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.3"
colorlog = "^4.2.1"
setuptools-autover = "^1.0.2"
luddite = "^1.0.1"
packaging = "^20.4"
python-box = "^5.3.0"

[tool.poetry.dev-dependencies]
Sphinx = "^4.0.2"
sphinx-autoapi = "^1.8.1"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
