#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['bapy']

package_data = \
{'': ['*']}

install_requires = \
['typer']

entry_points = \
{'console_scripts': ['bapy = bapy:app', 'localbin = bapy:localbin']}

setup(name='bapy',
      version='0.27.26',
      description='BAPY Package.',
      author='José',
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
