[tool.poetry]
name = "chistes_hub_malaga"
version = "0.1.0"
description = ""
authors = ["Pablo Martin Fernandez <pablo.martin.fernandez@pwc.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
googletrans = "4.0.0rc1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
