[tool.poetry]
name = "gwdc-python"
version = "0.1.0"
description = "API for GWDC modules"
authors = ["Thomas Reichardt <treichardt@swin.edu.au>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"
jwt = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
requests-mock = "^1.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
