[tool.poetry]
name = "gwcloud-python"
version = "0.1.0"
description = "Wrapper of GWDC API, used for interacting with the GWCloud endpoints"
authors = ["Thomas Reichardt <treichardt@swin.edu.au>"]

[tool.poetry.dependencies]
python = "^3.6"
gwdc-python = "^0.1.0"
requests = "^2.25.1"
jwt = "^1.2.0"
graphene-file-upload = "^1.3.0"

[tool.poetry.dev-dependencies]
gwdc-python = {path = "../gwdc-python/", develop = true}
pytest = "^5.2"
requests-mock = "^1.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
