[project]
name = "mozart-signal-parser"
version = "0.1.1"
description = ""
authors = [
    {name = "Sergey Anufrienko", email = "serg@anufrienko.net"},
]
dependencies = ["pytesseract~=0.3", "opencv-python~=4.5"]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]

[tool.poetry]
name = "mozart-signal-parser"
version = "0.1.1"
description = ""
authors = ["Sergey Anufrienko <serg@anufrienko.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pytesseract = "^0.3.7"
opencv-python = "^4.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
