# Generated by Django 3.1.5 on 2021-01-24 21:31

import djupiter.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djupiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Super Admin',
                'verbose_name_plural': 'Super Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djupiter.user',),
            managers=[
                ('objects', djupiter.managers.UserManager()),
            ],
        ),
    ]
