# Generated by Django 3.1.5 on 2021-01-25 20:42

import djupiter.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djupiter', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(default=djupiter.models._generate_code, max_length=4),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 21, 12, 0, 593177, tzinfo=utc)),
        ),
    ]
