# Generated by Django 3.1.5 on 2021-02-01 20:47

import djupiter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djupiter', '0004_auto_20210125_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=djupiter.models._30_mins_from_now),
        ),
    ]
