# Generated by Django 3.1.5 on 2021-02-18 20:03

import djupiter.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djupiter', '0007_auto_20210203_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commoner',
            fields=[
            ],
            options={
                'verbose_name': 'Commoner',
                'verbose_name_plural': 'Commoners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djupiter.user',),
            managers=[
                ('objects', djupiter.managers.UserManager()),
            ],
        ),
    ]
