[tool.poetry]
name = "raftel"
version = "0.2.0"
description = "package to plot s2id easily"
authors = ["mitbal <mit.iqi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
staticmap = "^0.5.5"
s2sphere = "^0.2.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
