
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T01:51:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "37348dcce2c0d421537b010eeca4ab66ea8b78d9",
 "version": "2.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
