
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-06T23:13:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a2bd08b25a1b0ca9a14de08092d6b3ce8952a75",
 "version": "3.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
