[tool.poetry]
name = "quiet-py-wasm"
version = "0.1.3"
description = "Python interface to WASM build of Quiet. Work in progress: Current not suitable for use."
authors = ["Martin Moxon"]
include = ["quiet_py_wasm/quiet-profiles.json", "quiet_py_wasm/quiet.wasm"]

[tool.poetry.dependencies]
python = "^3.8"
wasmer-compiler-cranelift = "1.0.0"
wasmer = "^1.0.0"
PyAudio = "^0.2.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
