
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T16:47:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ae6668ec323420ca8d14b206534c94fffc5ae91",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
