[tool.poetry]
name = "hajkr-facebook-scraper"
version = "0.1.0"
description = ""
authors = ["Tadej Hribar"]

[tool.poetry.dependencies]
python = "^3.9"
facebook-scraper = "^0.2.41"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
