
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T17:32:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f284e15a5705d13e62706317f7e47f0e9b3fac7f",
 "version": "0.4.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
