[tool.isort]
profile = "black"

[tool.poetry]
name = "cli-ui"
version = "0.14.1"
description = "Build Nice User Interfaces In The Terminal"
readme = "README.rst"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
license = "BSD-3-Clause"
repository = "https://github.com/dmerejkowsky/python-cli-ui"
documentation = "https://dmerejkowsky.github.io/python-cli-ui/"

[tool.poetry.urls]
Changelog = "https://dmerejkowsky.github.io/python-cli-ui/changelog.html"
Issues = "https://github.com/dmerejkowsky/python-cli-ui/issues"

[tool.poetry.dependencies]
# Keep this in sync with .github/workflows/
python = "^3.6.2"
colorama = "^0.4.1"
tabulate = "^0.8.3"
unidecode = "^1.0.23"

[tool.poetry.dev-dependencies]
# general
invoke = "^1.5"

# doc
sphinx  = "^3.0.4"
ghp-import = "^0.5.5"

# linters
black = "21.5b0"
isort = "^5.7.0"
mypy = "^0.800"
flake8 = "^3.9.1"
flake8-bugbear = "^21.4.3"
pep8-naming = "^0.11.1"

# tests
attrs = "^19.3"
coverage = "^5.2"
pytest = "^6.2.1"
pytest-cov = "^2.10"
safety = "^1.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
