
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-07T04:22:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e0c69edc97ef5a194feba371aadd3d5e303d68a",
 "version": "4.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
