# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from common_pb2 import (
    Amount as common_pb2___Amount,
    EntityTypeValue as common_pb2___EntityTypeValue,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from integration_source_pb2 import (
    IntegrationSourceValue as integration_source_pb2___IntegrationSourceValue,
)

from typing import (
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ActionStateValue = typing___NewType('ActionStateValue', builtin___int)
type___ActionStateValue = ActionStateValue
ActionState: _ActionState
class _ActionState(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ActionStateValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    ACTION_STATE_UNSPECIFIED = typing___cast(ActionStateValue, 0)
    ACTION_STATE_ENABLED = typing___cast(ActionStateValue, 1)
    ACTION_STATE_DISABLED = typing___cast(ActionStateValue, 2)
ACTION_STATE_UNSPECIFIED = typing___cast(ActionStateValue, 0)
ACTION_STATE_ENABLED = typing___cast(ActionStateValue, 1)
ACTION_STATE_DISABLED = typing___cast(ActionStateValue, 2)
type___ActionState = ActionState

ActionInvocationStatusValue = typing___NewType('ActionInvocationStatusValue', builtin___int)
type___ActionInvocationStatusValue = ActionInvocationStatusValue
ActionInvocationStatus: _ActionInvocationStatus
class _ActionInvocationStatus(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ActionInvocationStatusValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    ACTION_INVOCATION_STATUS_UNSPECIFIED = typing___cast(ActionInvocationStatusValue, 0)
    ACTION_INVOCATION_STATUS_SUCCESS = typing___cast(ActionInvocationStatusValue, 1)
    ACTION_INVOCATION_STATUS_FAILED = typing___cast(ActionInvocationStatusValue, 2)
ACTION_INVOCATION_STATUS_UNSPECIFIED = typing___cast(ActionInvocationStatusValue, 0)
ACTION_INVOCATION_STATUS_SUCCESS = typing___cast(ActionInvocationStatusValue, 1)
ACTION_INVOCATION_STATUS_FAILED = typing___cast(ActionInvocationStatusValue, 2)
type___ActionInvocationStatus = ActionInvocationStatus

ActionTypeValue = typing___NewType('ActionTypeValue', builtin___int)
type___ActionTypeValue = ActionTypeValue
ActionType: _ActionType
class _ActionType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ActionTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    ACTION_TYPE_UNSPECIFIED = typing___cast(ActionTypeValue, 0)
    ACTION_TYPE_CHARGE_REFUND = typing___cast(ActionTypeValue, 1)
    ACTION_TYPE_SUBSCRIPTION_TRIAL_UPDATE = typing___cast(ActionTypeValue, 100)
    ACTION_TYPE_COUPON_APPLY = typing___cast(ActionTypeValue, 200)
    ACTION_TYPE_OPPORTUNITY_CREATE = typing___cast(ActionTypeValue, 300)
    ACTION_TYPE_WEBHOOK = typing___cast(ActionTypeValue, 10000)
ACTION_TYPE_UNSPECIFIED = typing___cast(ActionTypeValue, 0)
ACTION_TYPE_CHARGE_REFUND = typing___cast(ActionTypeValue, 1)
ACTION_TYPE_SUBSCRIPTION_TRIAL_UPDATE = typing___cast(ActionTypeValue, 100)
ACTION_TYPE_COUPON_APPLY = typing___cast(ActionTypeValue, 200)
ACTION_TYPE_OPPORTUNITY_CREATE = typing___cast(ActionTypeValue, 300)
ACTION_TYPE_WEBHOOK = typing___cast(ActionTypeValue, 10000)
type___ActionType = ActionType

class ChargeRefundParams(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    reason: typing___Text = ...

    @property
    def amount(self) -> common_pb2___Amount: ...

    def __init__(self,
        *,
        amount : typing___Optional[common_pb2___Amount] = None,
        reason : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"amount",b"amount"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"amount",b"amount",u"reason",b"reason"]) -> None: ...
type___ChargeRefundParams = ChargeRefundParams

class SubscriptionTrialUpdateParams(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def trial_end_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        trial_end_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"trial_end_at",b"trial_end_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"trial_end_at",b"trial_end_at"]) -> None: ...
type___SubscriptionTrialUpdateParams = SubscriptionTrialUpdateParams

class CouponApplyParams(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    coupon_id: typing___Text = ...

    def __init__(self,
        *,
        coupon_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"coupon_id",b"coupon_id"]) -> None: ...
type___CouponApplyParams = CouponApplyParams

class OpportunityCreateParams(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    stage_name: typing___Text = ...
    owner_id: typing___Text = ...
    opportunity_type: typing___Text = ...

    @property
    def closed_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def amount(self) -> common_pb2___Amount: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        closed_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        amount : typing___Optional[common_pb2___Amount] = None,
        stage_name : typing___Optional[typing___Text] = None,
        owner_id : typing___Optional[typing___Text] = None,
        opportunity_type : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"amount",b"amount",u"closed_at",b"closed_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"amount",b"amount",u"closed_at",b"closed_at",u"name",b"name",u"opportunity_type",b"opportunity_type",u"owner_id",b"owner_id",u"stage_name",b"stage_name"]) -> None: ...
type___OpportunityCreateParams = OpportunityCreateParams

class WebhookParams(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    url: typing___Text = ...

    def __init__(self,
        *,
        url : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"url",b"url"]) -> None: ...
type___WebhookParams = WebhookParams

class ActionParams(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    force: builtin___bool = ...

    @property
    def charge_refund_params(self) -> type___ChargeRefundParams: ...

    @property
    def subscription_trial_update_params(self) -> type___SubscriptionTrialUpdateParams: ...

    @property
    def coupon_apply_params(self) -> type___CouponApplyParams: ...

    @property
    def opportunity_create_params(self) -> type___OpportunityCreateParams: ...

    @property
    def webhook_params(self) -> type___WebhookParams: ...

    def __init__(self,
        *,
        charge_refund_params : typing___Optional[type___ChargeRefundParams] = None,
        subscription_trial_update_params : typing___Optional[type___SubscriptionTrialUpdateParams] = None,
        coupon_apply_params : typing___Optional[type___CouponApplyParams] = None,
        opportunity_create_params : typing___Optional[type___OpportunityCreateParams] = None,
        webhook_params : typing___Optional[type___WebhookParams] = None,
        force : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"charge_refund_params",b"charge_refund_params",u"coupon_apply_params",b"coupon_apply_params",u"opportunity_create_params",b"opportunity_create_params",u"params",b"params",u"subscription_trial_update_params",b"subscription_trial_update_params",u"webhook_params",b"webhook_params"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"charge_refund_params",b"charge_refund_params",u"coupon_apply_params",b"coupon_apply_params",u"force",b"force",u"opportunity_create_params",b"opportunity_create_params",u"params",b"params",u"subscription_trial_update_params",b"subscription_trial_update_params",u"webhook_params",b"webhook_params"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"params",b"params"]) -> typing_extensions___Literal["charge_refund_params","subscription_trial_update_params","coupon_apply_params","opportunity_create_params","webhook_params"]: ...
type___ActionParams = ActionParams

class ThirdPartyActionInvocationResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class HeadersEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___HeadersEntry = HeadersEntry

    class MetaEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___MetaEntry = MetaEntry

    body: typing___Text = ...

    @property
    def headers(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    @property
    def meta(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        headers : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        meta : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        body : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"body",b"body",u"headers",b"headers",u"meta",b"meta"]) -> None: ...
type___ThirdPartyActionInvocationResponse = ThirdPartyActionInvocationResponse

class ActionConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    title: typing___Text = ...
    source: integration_source_pb2___IntegrationSourceValue = ...
    entity_type: common_pb2___EntityTypeValue = ...
    created_by_organization_user: typing___Text = ...
    action_state: type___ActionStateValue = ...
    action_type: type___ActionTypeValue = ...
    description: typing___Text = ...

    @property
    def default_action_params(self) -> type___ActionParams: ...

    def __init__(self,
        *,
        title : typing___Optional[typing___Text] = None,
        source : typing___Optional[integration_source_pb2___IntegrationSourceValue] = None,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        created_by_organization_user : typing___Optional[typing___Text] = None,
        default_action_params : typing___Optional[type___ActionParams] = None,
        action_state : typing___Optional[type___ActionStateValue] = None,
        action_type : typing___Optional[type___ActionTypeValue] = None,
        description : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"default_action_params",b"default_action_params"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_state",b"action_state",u"action_type",b"action_type",u"created_by_organization_user",b"created_by_organization_user",u"default_action_params",b"default_action_params",u"description",b"description",u"entity_type",b"entity_type",u"source",b"source",u"title",b"title"]) -> None: ...
type___ActionConfig = ActionConfig
