
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-04T14:47:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "611923e2d718350b8e8443d0d94c853c18b91574",
 "version": "2021.06.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
