[tool.poetry]
name = "aaronsteers"
version = "0.0.1-alpha0"
description = "It's me, AJ! Hi."
authors = ["AJ Steers <aaronsteers@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
