
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-07T05:34:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1fc0aa99cb1467303662f8ae328fcd469e08b85c",
 "version": "0.7.0.post.dev158"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
