---
sgabios_dir: /usr/share/sgabios/
libvirt_service_name: libvirtd
required_packages:
 - qemu-img
 - kernel-tools
 - qemu-kvm
 - sgabios
 - sgabios-bin
 - libvirt
 - libvirt-client
 - libvirt-daemon
 - libvirt-daemon-config-network
 - libvirt-daemon-config-nwfilter
 - libvirt-daemon-driver-network
 - libvirt-daemon-driver-nodedev
 - libvirt-daemon-driver-nwfilter
 - libvirt-daemon-driver-qemu
 - libvirt-daemon-driver-secret
 - libvirt-daemon-driver-storage
 - libvirt-daemon-kvm
 - pkgconfig
 - libvirt-devel
 - trousers
 # TODO(mgoddard): Remove pin after
 # https://bugzilla.redhat.com/show_bug.cgi?id=1961562 is fixed
 - edk2-ovmf-20200602gitca407c7246bf-4.el8
test_vm_emulator: "/usr/libexec/qemu-kvm"
