[tool.poetry]
name = "vag"
version = "0.1.44"
description = "vagrant utility cli tool"
authors = ["Seven Tella <7onetella@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
Click = "^7.1.2"
untangle = "^1.1.1"
jinja2 = "^2.11.2"
requests = "^2.25.1"
pyyaml = "^5.4.1"
sqlalchemy = "^1.4.15"
psycopg2 = "^2.8.6"
pylint = "^2.8.2"
giteapy = "^1.0.8"

[tool.poetry.scripts]
vag = "vag.console.application:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
