[tool.poetry]
name = "stonewave-sql-udtfs"
version = "0.4.1"
description = ""
authors = ["Yue Ni <yni@yanhuangdata.com>"]
packages = [
    { include = "stonewave" },
]
include = [
    "stonewave/sql/udtfs/version.py"
]
license = "Proprietary"
homepage = "https://www.yanhuangdata.com/"

[tool.poetry.dependencies]
python = "^3.9"
setuptools = ">=41.2.0"
wheel = ">=0.35.1"
pyarrow = "4.0.0"

# !!PLEASE KEEP DEPENDENCIES FOR DIFFERENT FUNCTIONS SEPARATED!!
# so that it is eaiser to create different virtual envs for them later

# dependencies for `faker` table function
faker = "^5.0.2"
faker-cloud = "^0.1"
faker_web = "^0.3.1"
faker_wifi_essid = "^0.2.0"
faker_vehicle = "^0.1.3"
faker_microservice = "^2.0.0"
faker_credit_score = "^0.3.0"
parse = "^1.18.0"
pygrok = "^1.0.0"
transitions = "^0.8.3"
pandas = "^1.1.3"
structlog = "^20.2.0"
openpyxl = "^3.0.6"
kaitaistruct = "^0.9"
wheel-filename = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
black = {version = "^20.8b1", allow-prereleases = true}

[[tool.poetry.source]]
name = "yh-repo"
url = "https://yanhuangdata.github.io/pypi/simple/"

[tool.pytest.ini_options]
minversion = "6.0"
junit_family = "xunit2"
log_cli = "true"
# https://docs.pytest.org/en/stable/logging.html
log_cli_level = "CRITICAL"
log_level = "INFO"
log_format = "%(asctime)s (%(threadName)-10s) %(filename)s:%(lineno)d %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
addopts = "--junitxml=./build/py_table_funcs_pytest_report.xml"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.poetry.scripts]
sw_py_udtf = 'stonewave.sql.udtfs.main:execute_command'