image: "python:3.9"

before_script:
  - python --version
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements_rnd.txt
  - pip install .

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint src/mrtinydbutils/*.py

mypy:
  stage: Static Analysis
  script:
  - mypy src/mrtinydbutils/*.py

unit_test:
  stage: Test
  script:
  - coverage run -m unittest tests/test_tables.py

coverage:
  stage: Test
  script:
  - coverage run -m unittest tests/test_tables.py
  - coverage report -m --include='*/mrtinydbutils/*'
