#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flake8_comments']

package_data = \
{'': ['*']}

install_requires = \
['flake8']

extras_require = \
{'test': ['pytest', 'pytest-cov']}

entry_points = \
{'flake8.extension': ['CM00 = flake8_comments:Checker']}

setup(name='flake8-comments',
      version='0.1.2',
      description='Find redundant comments in Python code',
      author='Gram',
      author_email='gram@orsinium.dev',
      url='https://github.com/orsinium-labs/flake8-comments',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
