# Generated by Django 3.1.7 on 2021-05-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smpl_fias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIAS_City',
            fields=[
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('smpl_fias.fias_object',),
        ),
        migrations.CreateModel(
            name='FIAS_District',
            fields=[
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('smpl_fias.fias_object',),
        ),
    ]
