[tool.poetry]
name = "django-rest-mfa"
version = "0.1.0"
description = "Django Rest Framework Endpoints for MFA including TOTP and FIDO2"
authors = ["David Burke <david@burkesoftware.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fido2 = "^0.9.1"
djangorestframework = "^3.12.4"
pyotp = "^2.6.0"
user-agents = "^2.2.0"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
pylint-django = "^2.4.4"
django-sslserver = "^0.22"
model-bakery = "^1.3.1"
django-rest-auth = "^0.9.5"
ipdb = "^0.13.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
