# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: f99_erp_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='f99_erp_api.proto',
  package='f99_erp_api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x66\x39\x39_erp_api.proto\x12\x0b\x66\x39\x39_erp_api\"\xe0\x01\n\x15\x43reateSaleOrderParams\x12@\n\norder_line\x18\x01 \x03(\x0b\x32,.f99_erp_api.CreateSaleOrderParams.OrderLine\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cwarehouse_id\x18\x03 \x01(\x03\x12\x12\n\npartner_id\x18\x04 \x01(\x03\x12\x17\n\x0f\x63ommitment_date\x18\x05 \x01(\t\x1a\x34\n\tOrderLine\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\x12\x13\n\x0bproduct_qty\x18\x02 \x01(\x03\"&\n\x15\x43reateSaleOrderResult\x12\r\n\x05is_ok\x18\x01 \x01(\x08\x32h\n\tF99ErpApi\x12[\n\x11\x63reate_sale_order\x12\".f99_erp_api.CreateSaleOrderParams\x1a\".f99_erp_api.CreateSaleOrderResultb\x06proto3')
)




_CREATESALEORDERPARAMS_ORDERLINE = _descriptor.Descriptor(
  name='OrderLine',
  full_name='f99_erp_api.CreateSaleOrderParams.OrderLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='f99_erp_api.CreateSaleOrderParams.OrderLine.product_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_qty', full_name='f99_erp_api.CreateSaleOrderParams.OrderLine.product_qty', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=259,
)

_CREATESALEORDERPARAMS = _descriptor.Descriptor(
  name='CreateSaleOrderParams',
  full_name='f99_erp_api.CreateSaleOrderParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_line', full_name='f99_erp_api.CreateSaleOrderParams.order_line', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='f99_erp_api.CreateSaleOrderParams.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='f99_erp_api.CreateSaleOrderParams.warehouse_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partner_id', full_name='f99_erp_api.CreateSaleOrderParams.partner_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commitment_date', full_name='f99_erp_api.CreateSaleOrderParams.commitment_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CREATESALEORDERPARAMS_ORDERLINE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=259,
)


_CREATESALEORDERRESULT = _descriptor.Descriptor(
  name='CreateSaleOrderResult',
  full_name='f99_erp_api.CreateSaleOrderResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_ok', full_name='f99_erp_api.CreateSaleOrderResult.is_ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=299,
)

_CREATESALEORDERPARAMS_ORDERLINE.containing_type = _CREATESALEORDERPARAMS
_CREATESALEORDERPARAMS.fields_by_name['order_line'].message_type = _CREATESALEORDERPARAMS_ORDERLINE
DESCRIPTOR.message_types_by_name['CreateSaleOrderParams'] = _CREATESALEORDERPARAMS
DESCRIPTOR.message_types_by_name['CreateSaleOrderResult'] = _CREATESALEORDERRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSaleOrderParams = _reflection.GeneratedProtocolMessageType('CreateSaleOrderParams', (_message.Message,), {

  'OrderLine' : _reflection.GeneratedProtocolMessageType('OrderLine', (_message.Message,), {
    'DESCRIPTOR' : _CREATESALEORDERPARAMS_ORDERLINE,
    '__module__' : 'f99_erp_api_pb2'
    # @@protoc_insertion_point(class_scope:f99_erp_api.CreateSaleOrderParams.OrderLine)
    })
  ,
  'DESCRIPTOR' : _CREATESALEORDERPARAMS,
  '__module__' : 'f99_erp_api_pb2'
  # @@protoc_insertion_point(class_scope:f99_erp_api.CreateSaleOrderParams)
  })
_sym_db.RegisterMessage(CreateSaleOrderParams)
_sym_db.RegisterMessage(CreateSaleOrderParams.OrderLine)

CreateSaleOrderResult = _reflection.GeneratedProtocolMessageType('CreateSaleOrderResult', (_message.Message,), {
  'DESCRIPTOR' : _CREATESALEORDERRESULT,
  '__module__' : 'f99_erp_api_pb2'
  # @@protoc_insertion_point(class_scope:f99_erp_api.CreateSaleOrderResult)
  })
_sym_db.RegisterMessage(CreateSaleOrderResult)



_F99ERPAPI = _descriptor.ServiceDescriptor(
  name='F99ErpApi',
  full_name='f99_erp_api.F99ErpApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=301,
  serialized_end=405,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_sale_order',
    full_name='f99_erp_api.F99ErpApi.create_sale_order',
    index=0,
    containing_service=None,
    input_type=_CREATESALEORDERPARAMS,
    output_type=_CREATESALEORDERRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_F99ERPAPI)

DESCRIPTOR.services_by_name['F99ErpApi'] = _F99ERPAPI

# @@protoc_insertion_point(module_scope)
