
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-06T14:20:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5efbce3036f77a7a2a32ea49ede25388b08b8d4",
 "version": "2021.6.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
