
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T10:38:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8b05e5444de1274f3b8bfd0568cb4946c08f8fd",
 "version": "2482"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
