
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-01T21:14:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "801a1141ce438bf3b813dbef468712fa3feef1ba",
 "version": "1.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
